global:
  imageRegistry: "123456789012.dkr.ecr.us-east-1.amazonaws.com/suplab"

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:ACCOUNT:certificate/CERT_ID"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    external-dns.alpha.kubernetes.io/hostname: "vault.aether.example.com"
  host: vault.aether.example.com
  path: /

app:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT:role/aether-vault-role"
  secrets:
    existingSecret: "aether-vault-secrets"

serviceMonitor:
  enabled: true
