openshift:
  enabled: true

global:
  imageRegistry: "quay.io/suplab"

ingress:
  enabled: false

route:
  host: "vault.aether.apps.cluster.example.com"
  termination: edge
  insecureEdgeTerminationPolicy: Redirect

app:
  serviceAccount:
    annotations: {}

serviceMonitor:
  enabled: true
